# TODO: add an appropriate FROM line
FROM ???

# TODO: put your jar in the /opt directory in the image

# When the docker is run, execute /user/bin/java -jar /opt/constant-to-camel-1.0-SNAPSHOT-jar-with-dependencies.jar
ENTRYPOINT ["java", "-jar", "/opt/constant-to-camel-1.0-SNAPSHOT.jar"]

# The default argument when running a container is "THIS_IS_A_TEST_CONSTANT_NAME"
CMD ["THIS_IS_A_TEST_CONSTANT_NAME"]
